Convert slug to lowercase
id-mozilla/mozspace-jkt-backend pull request #14
Opened 2019-04-07 15:50 UTC by kei-001

Convert slug to lowercase

2019-04-07 15:51 UTC, kei-001 commented
Convert slug to lowercase

2019-04-13 03:03 UTC, jokosu10 commented
pak @kei-001,
setelah saya coba untuk yang slug eventnya, masi belum sesuai. Gambar uji coba terlampir. 

cc mas @dikyarga 
<img width="1269" alt="Screen Shot 2019-04-13 at 09 59 20" src="https://user-images.githubusercontent.com/7246784/56073767-41818280-5dd3-11e9-895c-ab49dd00e877.png">

2019-04-19 08:48 UTC, dikyarga commented
coba saya cek yak @jokosu10 
https://github.com/id-mozilla/mozspace-jkt-backend/issues/5

2019-10-13 10:04 UTC, mnirfan requested changes

2019-10-13 10:04 UTC, mnirfan commented on common/telegram/tele.js
> +const token = '782076025:AAF_oyQlg-dbnBbHtUHDK1JPlG4m4sKVVN0'; // need token bot chat
env nya di buat dari env variable ya (`process.env`)

2024-05-15 01:48 UTC, closed without merging